-- v8.0 commit 3 (U2): one-shot auto-expiring invite links.
--
-- Operator runs `npm run invite:new -- --member-limit=1 --expire-hours=24`
-- to mint a per-distribution invite link. The bot generates the link via
-- Bot API `createChatInviteLink` with `member_limit:1`; Telegram
-- auto-revokes after first use. Bot also captures `chat_join_request`
-- updates and stamps `used_by_telegram_id` + `used_at` on the matching
-- row so the operator can see who used which link.
--
-- This table is the only persistent record of invite-link provenance.
-- If a link wasn't generated by us, captures are no-ops (best-effort).
CREATE TABLE IF NOT EXISTS invite_links (
  id BIGSERIAL PRIMARY KEY,
  link TEXT NOT NULL UNIQUE,
  member_limit INTEGER,
  expire_date TIMESTAMPTZ,
  name TEXT,
  created_by_telegram_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  used_by_telegram_id BIGINT,
  used_at TIMESTAMPTZ
);

-- Lookups by `link` happen on every chat_join_request capture; the unique
-- index on `link` already covers that. No additional indexes needed.
