// v8.0 commit 3 (U2): per-distribution one-shot invite links.
//
// Wraps Bot API createChatInviteLink + DB persistence. Operator runs
// `npm run invite:new` to mint a link; the bot captures `chat_join_request`
// updates and calls recordInviteLinkUsed to stamp the row.
//
// Bot API references (verified against
// docs/runbook/telegram-snapshots/telegram-bot-api.html):
//   - createChatInviteLink (snapshot line 11344)
//     params: chat_id, name?, expire_date? (Unix int), member_limit? (1-99999),
//     creates_join_request?. Returns ChatInviteLink.
//   - ChatJoinRequest (snapshot line 5493)
//     field invite_link: ChatInviteLink — the link the user used to apply.
//
// Constraint: if creates_join_request:true, member_limit can't be set
// (Bot API enforces). We use member_limit:1 for one-shot semantics and
// leave creates_join_request unset; Request-to-Join is configured at the
// supergroup permission level.

type LoggerLike = Pick<Console, "info" | "warn" | "error">;

export interface GenerateInviteLinkInput {
  chatId: number;
  memberLimit?: number;
  expireHours?: number;
  name?: string;
  createdByTelegramId?: number | null;
}

export interface GeneratedInviteLink {
  link: string;
  memberLimit: number | null;
  expireDate: Date | null;
  name: string | null;
}

// Telegram caps name at 32 chars (snapshot 11366). Mint-side validation
// keeps the operator CLI from sending an over-long name and getting a 400.
const INVITE_LINK_NAME_MAX = 32;

export function buildExpireDateUnix(expireHours: number, now: Date = new Date()): number {
  return Math.floor(now.getTime() / 1000) + Math.floor(expireHours * 3600);
}

export function validateInviteLinkParams(input: {
  name?: string | null;
  memberLimit?: number | null;
}): void {
  if (input.name != null && input.name.length > INVITE_LINK_NAME_MAX) {
    throw new Error(
      `invite link name must be 0-${INVITE_LINK_NAME_MAX} chars (got ${input.name.length})`,
    );
  }
  if (
    input.memberLimit != null &&
    (input.memberLimit < 1 || input.memberLimit > 99_999)
  ) {
    throw new Error(
      `invite link member_limit must be 1-99999 (got ${input.memberLimit})`,
    );
  }
}

export async function generateInviteLink(
  input: GenerateInviteLinkInput,
  logger?: LoggerLike,
): Promise<GeneratedInviteLink> {
  validateInviteLinkParams({
    name: input.name ?? null,
    memberLimit: input.memberLimit ?? null,
  });

  const { eq } = await import("drizzle-orm");
  const { db } = await import("./storage/db.ts");
  const { inviteLinks } = await import("./storage/schema.ts");
  const { createTelegramInviteLink } = await import("./tools/telegramTools.ts");
  void eq;

  const expireDateUnix =
    input.expireHours != null && input.expireHours > 0
      ? buildExpireDateUnix(input.expireHours)
      : undefined;

  const result = await createTelegramInviteLink(
    {
      chatId: input.chatId,
      memberLimit: input.memberLimit,
      expireDate: expireDateUnix,
      name: input.name,
    },
    logger,
  );

  const expireDate = expireDateUnix != null ? new Date(expireDateUnix * 1000) : null;

  await db
    .insert(inviteLinks)
    .values({
      link: result.invite_link,
      memberLimit: input.memberLimit ?? null,
      expireDate,
      name: input.name ?? null,
      createdByTelegramId: input.createdByTelegramId ?? null,
    })
    .onConflictDoNothing({ target: inviteLinks.link });

  return {
    link: result.invite_link,
    memberLimit: input.memberLimit ?? null,
    expireDate,
    name: input.name ?? null,
  };
}

// Best-effort: stamp used_by/used_at on the matching row when a member
// joins via a link we minted. If the link wasn't generated by us,
// no-op (the row simply doesn't exist).
export async function recordInviteLinkUsed(
  link: string,
  telegramId: number,
  logger?: LoggerLike,
): Promise<void> {
  try {
    const { eq } = await import("drizzle-orm");
    const { db } = await import("./storage/db.ts");
    const { inviteLinks } = await import("./storage/schema.ts");
    await db
      .update(inviteLinks)
      .set({
        usedByTelegramId: telegramId,
        usedAt: new Date(),
      })
      .where(eq(inviteLinks.link, link));
  } catch (error) {
    // Never log the full link string — it's takedown-vector material.
    // Log a short fingerprint (last 6 chars) so an admin can correlate
    // with `invite_links` table without exposing a usable URL.
    logger?.warn?.(
      { error, linkSuffix: link.slice(-6), telegramId },
      "recordInviteLinkUsed failed",
    );
  }
}

// Fingerprint helper — exposes the last 6 chars of an invite link for
// log correlation without leaking a usable URL.
export function fingerprintInviteLink(link: string): string {
  return link.slice(-6);
}
